/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/f70UvPMax9p
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Tenor_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

tenor_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

export function ChannelPage() {
  return (
    <div className="grid grid-cols-[3fr_1fr] h-screen w-full">
      <div className="flex flex-col">
        <div className="flex-1 relative">
          <video
            className="w-full h-full object-cover"
            // src="https://www.youtube.com/c243b6b7-b610-4da3-9498-46d8b5951b42"
            controls
          />
          <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/50 to-transparent p-4 flex items-center justify-between text-white">
            <div className="flex items-center gap-2">
              <Button variant="ghost" size="icon">
                <PlayIcon className="w-6 h-6" />
              </Button>
              <Button variant="ghost" size="icon">
                <Volume2Icon className="w-6 h-6" />
              </Button>
              <Button variant="ghost" size="icon">
                <MaximizeIcon className="w-6 h-6" />
              </Button>
            </div>
            <div className="text-sm">1:23:45 / 2:00:00</div>
          </div>
        </div>
        <div className="bg-muted p-6 grid gap-4">
          <div className="flex items-center gap-4">
            <Avatar className="w-12 h-12 border">
              <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <div>
              <div className="font-semibold">Vercel Developers</div>
              <div className="text-muted-foreground text-sm">
                Building the Frontend Cloud
              </div>
            </div>
          </div>
          <div className="text-sm leading-relaxed">
            Join us as we dive into the latest features and capabilities of the
            Vercel platform. Our team of experts will showcase how Vercel
            empowers frontend developers to build, test, and deploy high-quality
            web applications efficiently and quickly.
          </div>
        </div>
      </div>
      <div className="bg-muted p-4 flex flex-col gap-4 overflow-auto">
        <div className="text-lg font-semibold">Live Chat</div>
        <div className="flex items-start gap-3">
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
          <div className="bg-background rounded-lg p-3 text-sm">
            <div className="font-semibold">@shadcn</div>
            <div>This is so cool! Can't wait to try out the new features.</div>
          </div>
        </div>
        <div className="flex items-start gap-3">
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" alt="@jaredpalmer" />
            <AvatarFallback>JP</AvatarFallback>
          </Avatar>
          <div className="bg-background rounded-lg p-3 text-sm">
            <div className="font-semibold">@jaredpalmer</div>
            <div>Excited to see what the Vercel team has been working on!</div>
          </div>
        </div>
        <div className="flex items-start gap-3">
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" alt="@maxleiter" />
            <AvatarFallback>ML</AvatarFallback>
          </Avatar>
          <div className="bg-background rounded-lg p-3 text-sm">
            <div className="font-semibold">@maxleiter</div>
            <div>
              The frontend cloud sounds like a game-changer. Can't wait to learn
              more!
            </div>
          </div>
        </div>
        <div className="flex items-start gap-3">
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" alt="@shuding_" />
            <AvatarFallback>SD</AvatarFallback>
          </Avatar>
          <div className="bg-background rounded-lg p-3 text-sm">
            <div className="font-semibold">@shuding_</div>
            <div>
              This is going to be huge for the web development community. Kudos
              to the Vercel team!
            </div>
          </div>
        </div>
        <div className="flex-1 flex items-end">
          <Textarea
            placeholder="Type your message..."
            className="w-full rounded-lg p-3 border border-input bg-background"
          />
        </div>
      </div>
    </div>
  );
}

function MaximizeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 3H5a2 2 0 0 0-2 2v3" />
      <path d="M21 8V5a2 2 0 0 0-2-2h-3" />
      <path d="M3 16v3a2 2 0 0 0 2 2h3" />
      <path d="M16 21h3a2 2 0 0 0 2-2v-3" />
    </svg>
  );
}

function PlayIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  );
}

function Volume2Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
      <path d="M15.54 8.46a5 5 0 0 1 0 7.07" />
      <path d="M19.07 4.93a10 10 0 0 1 0 14.14" />
    </svg>
  );
}
