/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wVaTzWtBSaS
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Card } from "@/components/ui/card";
import { Link } from "react-router-dom";

export function ChannelCard() {
  const channelId = "1";

  return (
    <Card className="w-full max-w-sm rounded-lg overflow-hidden">
      <div className="relative">
        <img
          src="/placeholder.svg"
          alt="Twitch Channel"
          width="400"
          height="200"
          className="w-full h-[200px] object-cover"
          style={{ aspectRatio: "400/200", objectFit: "cover" }}
        />
        <div className="absolute bottom-0 left-0 w-full px-4 py-3 bg-gradient-to-t from-black/70 to-transparent">
          <div className="flex items-center justify-between text-white">
            <div className="flex items-center gap-2">
              <div className="bg-primary px-2 py-1 rounded-md text-sm font-medium text-primary-foreground">
                Live
              </div>
              <div className="text-lg font-semibold">Twitch Channel</div>
            </div>
            <div className="bg-primary px-2 py-1 rounded-md text-sm font-medium text-primary-foreground">
              1.2K viewers
            </div>
          </div>
        </div>
      </div>
      <div className="p-4 bg-card text-card-foreground">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" alt="Channel Avatar" />
              <AvatarFallback>TC</AvatarFallback>
            </Avatar>
            <div>
              <div className="font-medium">Twitch Channel</div>
              <div className="text-sm text-muted-foreground">
                @twitchchannel
              </div>
            </div>
          </div>
          <Link
            to={`/channels/${channelId}`}
            className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline"
          >
            Visit
            <ArrowRightIcon className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </Card>
  );
}

function ArrowRightIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}
