/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/otXUjCWq4FW
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";

export function GoogleLogin() {
  return (
    <Button
      variant="outline"
      className="flex items-center justify-center gap-2"
      onClick={onClick}
    >
      <ChromeIcon className="h-5 w-5" />
      Sign in with Google
    </Button>
  );
}

function onClick() {
  const clientId =
    "1050912560060-oh6prn9t68odupt6rr139lr4pf5oqcpl.apps.googleusercontent.com";
  const redirectUri = `${location.protocol}//${location.hostname}${
    location.port ? `:${location.port}` : ""
  }/redirect/google`;
  const responseType = "code";
  const scope =
    "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile";
  const state = randomString(16);
  const accessType = "offline";

  const url = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${clientId}&redirect_uri=${redirectUri}&response_type=${responseType}&scope=${scope}`;

  if (!clientId || !redirectUri || !scope || !responseType) {
    console.error("Google OAuth environment variables are missing.");
    return;
  }

  window.location.href = url;
}

function ChromeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  );
}
function randomString(arg0: number) {
  return Math.random()
    .toString(36)
    .substring(2, 2 + arg0);
}
