/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bdc12d3920cf46e8B27d88f7bc660261Request
 */
export interface Bdc12d3920cf46e8B27d88f7bc660261Request {
    [key: string]: any | any;
    /**
     * access_token or refresh_token
     * @type {string}
     * @memberof Bdc12d3920cf46e8B27d88f7bc660261Request
     */
    token: string;
}

/**
 * Check if a given object implements the Bdc12d3920cf46e8B27d88f7bc660261Request interface.
 */
export function instanceOfBdc12d3920cf46e8B27d88f7bc660261Request(value: object): value is Bdc12d3920cf46e8B27d88f7bc660261Request {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function Bdc12d3920cf46e8B27d88f7bc660261RequestFromJSON(json: any): Bdc12d3920cf46e8B27d88f7bc660261Request {
    return Bdc12d3920cf46e8B27d88f7bc660261RequestFromJSONTyped(json, false);
}

export function Bdc12d3920cf46e8B27d88f7bc660261RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bdc12d3920cf46e8B27d88f7bc660261Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'token': json['token'],
    };
}

export function Bdc12d3920cf46e8B27d88f7bc660261RequestToJSON(value?: Bdc12d3920cf46e8B27d88f7bc660261Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'token': value['token'],
    };
}

