/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bdc12d3920cf46e8B27d88f7bc660261200Response
 */
export interface Bdc12d3920cf46e8B27d88f7bc660261200Response {
    /**
     * 
     * @type {string}
     * @memberof Bdc12d3920cf46e8B27d88f7bc660261200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the Bdc12d3920cf46e8B27d88f7bc660261200Response interface.
 */
export function instanceOfBdc12d3920cf46e8B27d88f7bc660261200Response(value: object): value is Bdc12d3920cf46e8B27d88f7bc660261200Response {
    return true;
}

export function Bdc12d3920cf46e8B27d88f7bc660261200ResponseFromJSON(json: any): Bdc12d3920cf46e8B27d88f7bc660261200Response {
    return Bdc12d3920cf46e8B27d88f7bc660261200ResponseFromJSONTyped(json, false);
}

export function Bdc12d3920cf46e8B27d88f7bc660261200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bdc12d3920cf46e8B27d88f7bc660261200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Bdc12d3920cf46e8B27d88f7bc660261200ResponseToJSON(value?: Bdc12d3920cf46e8B27d88f7bc660261200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

