/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskRequest
 */
export interface CreateTaskRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    dueDate?: string;
}

/**
 * Check if a given object implements the CreateTaskRequest interface.
 */
export function instanceOfCreateTaskRequest(value: object): value is CreateTaskRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function CreateTaskRequestFromJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestFromJSONTyped(json, false);
}

export function CreateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'title': json['title'],
        'description': json['description'],
        'dueDate': json['due_date'] == null ? undefined : json['due_date'],
    };
}

export function CreateTaskRequestToJSON(value?: CreateTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'title': value['title'],
        'description': value['description'],
        'due_date': value['dueDate'],
    };
}

