/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFile200ResponseInner
 */
export interface CreateFile200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    pk?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    sk?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    entityType?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    size?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    bucket?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFile200ResponseInner
     */
    uploadedAt?: string;
}

/**
 * Check if a given object implements the CreateFile200ResponseInner interface.
 */
export function instanceOfCreateFile200ResponseInner(value: object): value is CreateFile200ResponseInner {
    return true;
}

export function CreateFile200ResponseInnerFromJSON(json: any): CreateFile200ResponseInner {
    return CreateFile200ResponseInnerFromJSONTyped(json, false);
}

export function CreateFile200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFile200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'pk': json['pk'] == null ? undefined : json['pk'],
        'sk': json['sk'] == null ? undefined : json['sk'],
        'entityType': json['entity_type'] == null ? undefined : json['entity_type'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'key': json['key'] == null ? undefined : json['key'],
        'uploadedAt': json['uploaded_at'] == null ? undefined : json['uploaded_at'],
    };
}

export function CreateFile200ResponseInnerToJSON(value?: CreateFile200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pk': value['pk'],
        'sk': value['sk'],
        'entity_type': value['entityType'],
        'name': value['name'],
        'size': value['size'],
        'bucket': value['bucket'],
        'key': value['key'],
        'uploaded_at': value['uploadedAt'],
    };
}

