/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTask201Response
 */
export interface CreateTask201Response {
    /**
     * 
     * @type {string}
     * @memberof CreateTask201Response
     */
    message?: string;
}

/**
 * Check if a given object implements the CreateTask201Response interface.
 */
export function instanceOfCreateTask201Response(value: object): value is CreateTask201Response {
    return true;
}

export function CreateTask201ResponseFromJSON(json: any): CreateTask201Response {
    return CreateTask201ResponseFromJSONTyped(json, false);
}

export function CreateTask201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTask201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CreateTask201ResponseToJSON(value?: CreateTask201Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

