/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateChatRequest
 */
export interface CreateChatRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateChatRequest
     */
    message: string;
    /**
     * members email, only when create chatroom(first message)
     * @type {Array<string>}
     * @memberof CreateChatRequest
     */
    members?: Array<string>;
}

/**
 * Check if a given object implements the CreateChatRequest interface.
 */
export function instanceOfCreateChatRequest(value: object): value is CreateChatRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CreateChatRequestFromJSON(json: any): CreateChatRequest {
    return CreateChatRequestFromJSONTyped(json, false);
}

export function CreateChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'message': json['message'],
        'members': json['members'] == null ? undefined : json['members'],
    };
}

export function CreateChatRequestToJSON(value?: CreateChatRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'message': value['message'],
        'members': value['members'],
    };
}

