/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownloadFile200Response
 */
export interface DownloadFile200Response {
    /**
     * 
     * @type {string}
     * @memberof DownloadFile200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the DownloadFile200Response interface.
 */
export function instanceOfDownloadFile200Response(value: object): value is DownloadFile200Response {
    return true;
}

export function DownloadFile200ResponseFromJSON(json: any): DownloadFile200Response {
    return DownloadFile200ResponseFromJSONTyped(json, false);
}

export function DownloadFile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownloadFile200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function DownloadFile200ResponseToJSON(value?: DownloadFile200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

