/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface E7dc84b79c5642dcAb7cCe778d7851b3200Response
 */
export interface E7dc84b79c5642dcAb7cCe778d7851b3200Response {
    /**
     * 
     * @type {string}
     * @memberof E7dc84b79c5642dcAb7cCe778d7851b3200Response
     */
    accessToken?: string;
    /**
     * 
     * @type {number}
     * @memberof E7dc84b79c5642dcAb7cCe778d7851b3200Response
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof E7dc84b79c5642dcAb7cCe778d7851b3200Response
     */
    tokenType?: string;
    /**
     * 
     * @type {string}
     * @memberof E7dc84b79c5642dcAb7cCe778d7851b3200Response
     */
    scope?: string;
}

/**
 * Check if a given object implements the E7dc84b79c5642dcAb7cCe778d7851b3200Response interface.
 */
export function instanceOfE7dc84b79c5642dcAb7cCe778d7851b3200Response(value: object): value is E7dc84b79c5642dcAb7cCe778d7851b3200Response {
    return true;
}

export function E7dc84b79c5642dcAb7cCe778d7851b3200ResponseFromJSON(json: any): E7dc84b79c5642dcAb7cCe778d7851b3200Response {
    return E7dc84b79c5642dcAb7cCe778d7851b3200ResponseFromJSONTyped(json, false);
}

export function E7dc84b79c5642dcAb7cCe778d7851b3200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): E7dc84b79c5642dcAb7cCe778d7851b3200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function E7dc84b79c5642dcAb7cCe778d7851b3200ResponseToJSON(value?: E7dc84b79c5642dcAb7cCe778d7851b3200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'token_type': value['tokenType'],
        'scope': value['scope'],
    };
}

