/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMe200Response
 */
export interface GetMe200Response {
    /**
     * 
     * @type {string}
     * @memberof GetMe200Response
     */
    email: string;
}

/**
 * Check if a given object implements the GetMe200Response interface.
 */
export function instanceOfGetMe200Response(value: object): value is GetMe200Response {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function GetMe200ResponseFromJSON(json: any): GetMe200Response {
    return GetMe200ResponseFromJSONTyped(json, false);
}

export function GetMe200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMe200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function GetMe200ResponseToJSON(value?: GetMe200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
    };
}

