/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleAuthorizeRequest
 */
export interface GoogleAuthorizeRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof GoogleAuthorizeRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof GoogleAuthorizeRequest
     */
    locale?: string;
}

/**
 * Check if a given object implements the GoogleAuthorizeRequest interface.
 */
export function instanceOfGoogleAuthorizeRequest(value: object): value is GoogleAuthorizeRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function GoogleAuthorizeRequestFromJSON(json: any): GoogleAuthorizeRequest {
    return GoogleAuthorizeRequestFromJSONTyped(json, false);
}

export function GoogleAuthorizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleAuthorizeRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'code': json['code'],
        'locale': json['locale'] == null ? undefined : json['locale'],
    };
}

export function GoogleAuthorizeRequestToJSON(value?: GoogleAuthorizeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'code': value['code'],
        'locale': value['locale'],
    };
}

