/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNotifications200ResponseInner
 */
export interface ListNotifications200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListNotifications200ResponseInner
     */
    userEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ListNotifications200ResponseInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListNotifications200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListNotifications200ResponseInner
     */
    isRead: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListNotifications200ResponseInner
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ListNotifications200ResponseInner
     */
    description: string;
}

/**
 * Check if a given object implements the ListNotifications200ResponseInner interface.
 */
export function instanceOfListNotifications200ResponseInner(value: object): value is ListNotifications200ResponseInner {
    if (!('userEmail' in value) || value['userEmail'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ListNotifications200ResponseInnerFromJSON(json: any): ListNotifications200ResponseInner {
    return ListNotifications200ResponseInnerFromJSONTyped(json, false);
}

export function ListNotifications200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNotifications200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userEmail': json['user_email'],
        'createdAt': json['created_at'],
        'id': json['id'],
        'isRead': json['is_read'],
        'title': json['title'],
        'description': json['description'],
    };
}

export function ListNotifications200ResponseInnerToJSON(value?: ListNotifications200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_email': value['userEmail'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'is_read': value['isRead'],
        'title': value['title'],
        'description': value['description'],
    };
}

