/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListIssues200ResponseInner
 */
export interface ListIssues200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListIssues200ResponseInner
     */
    userEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ListIssues200ResponseInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListIssues200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListIssues200ResponseInner
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ListIssues200ResponseInner
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListIssues200ResponseInner
     */
    subscribers?: Array<string>;
}

/**
 * Check if a given object implements the ListIssues200ResponseInner interface.
 */
export function instanceOfListIssues200ResponseInner(value: object): value is ListIssues200ResponseInner {
    if (!('userEmail' in value) || value['userEmail'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ListIssues200ResponseInnerFromJSON(json: any): ListIssues200ResponseInner {
    return ListIssues200ResponseInnerFromJSONTyped(json, false);
}

export function ListIssues200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListIssues200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userEmail': json['user_email'],
        'createdAt': json['created_at'],
        'id': json['id'],
        'title': json['title'],
        'description': json['description'],
        'subscribers': json['subscribers'] == null ? undefined : json['subscribers'],
    };
}

export function ListIssues200ResponseInnerToJSON(value?: ListIssues200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_email': value['userEmail'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'subscribers': value['subscribers'],
    };
}

