/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListFile200ResponseInner
 */
export interface ListFile200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    size?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    bucket?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof ListFile200ResponseInner
     */
    uploadedAt?: string;
}

/**
 * Check if a given object implements the ListFile200ResponseInner interface.
 */
export function instanceOfListFile200ResponseInner(value: object): value is ListFile200ResponseInner {
    return true;
}

export function ListFile200ResponseInnerFromJSON(json: any): ListFile200ResponseInner {
    return ListFile200ResponseInnerFromJSONTyped(json, false);
}

export function ListFile200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFile200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userEmail': json['user_email'] == null ? undefined : json['user_email'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'key': json['key'] == null ? undefined : json['key'],
        'uploadedAt': json['uploaded_at'] == null ? undefined : json['uploaded_at'],
    };
}

export function ListFile200ResponseInnerToJSON(value?: ListFile200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_email': value['userEmail'],
        'id': value['id'],
        'created_at': value['createdAt'],
        'name': value['name'],
        'size': value['size'],
        'bucket': value['bucket'],
        'key': value['key'],
        'uploaded_at': value['uploadedAt'],
    };
}

