/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListChatrooms200ResponseInner
 */
export interface ListChatrooms200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListChatrooms200ResponseInner
     */
    roomId: string;
    /**
     * 
     * @type {string}
     * @memberof ListChatrooms200ResponseInner
     */
    userEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ListChatrooms200ResponseInner
     */
    lastChattedAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListChatrooms200ResponseInner
     */
    lastMessage: string;
    /**
     * 
     * @type {number}
     * @memberof ListChatrooms200ResponseInner
     */
    badgeCount: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListChatrooms200ResponseInner
     */
    roomName?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ListChatrooms200ResponseInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ListChatrooms200ResponseInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the ListChatrooms200ResponseInner interface.
 */
export function instanceOfListChatrooms200ResponseInner(value: object): value is ListChatrooms200ResponseInner {
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('userEmail' in value) || value['userEmail'] === undefined) return false;
    if (!('lastChattedAt' in value) || value['lastChattedAt'] === undefined) return false;
    if (!('lastMessage' in value) || value['lastMessage'] === undefined) return false;
    if (!('badgeCount' in value) || value['badgeCount'] === undefined) return false;
    return true;
}

export function ListChatrooms200ResponseInnerFromJSON(json: any): ListChatrooms200ResponseInner {
    return ListChatrooms200ResponseInnerFromJSONTyped(json, false);
}

export function ListChatrooms200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListChatrooms200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'roomId': json['room_id'],
        'userEmail': json['user_email'],
        'lastChattedAt': json['last_chatted_at'],
        'lastMessage': json['last_message'],
        'badgeCount': json['badge_count'],
        'roomName': json['room_name'] == null ? undefined : json['room_name'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ListChatrooms200ResponseInnerToJSON(value?: ListChatrooms200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'room_id': value['roomId'],
        'user_email': value['userEmail'],
        'last_chatted_at': value['lastChattedAt'],
        'last_message': value['lastMessage'],
        'badge_count': value['badgeCount'],
        'room_name': value['roomName'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

