/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListFiles200ResponseInner
 */
export interface ListFiles200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    userEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    size: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    bucket: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ListFiles200ResponseInner
     */
    uploadedAt: string;
}

/**
 * Check if a given object implements the ListFiles200ResponseInner interface.
 */
export function instanceOfListFiles200ResponseInner(value: object): value is ListFiles200ResponseInner {
    if (!('userEmail' in value) || value['userEmail'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('uploadedAt' in value) || value['uploadedAt'] === undefined) return false;
    return true;
}

export function ListFiles200ResponseInnerFromJSON(json: any): ListFiles200ResponseInner {
    return ListFiles200ResponseInnerFromJSONTyped(json, false);
}

export function ListFiles200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListFiles200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'userEmail': json['user_email'],
        'id': json['id'],
        'createdAt': json['created_at'],
        'name': json['name'],
        'size': json['size'],
        'bucket': json['bucket'],
        'key': json['key'],
        'uploadedAt': json['uploaded_at'],
    };
}

export function ListFiles200ResponseInnerToJSON(value?: ListFiles200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user_email': value['userEmail'],
        'id': value['id'],
        'created_at': value['createdAt'],
        'name': value['name'],
        'size': value['size'],
        'bucket': value['bucket'],
        'key': value['key'],
        'uploaded_at': value['uploadedAt'],
    };
}

