/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListChats200ResponseInner
 */
export interface ListChats200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListChats200ResponseInner
     */
    roomId: string;
    /**
     * 
     * @type {string}
     * @memberof ListChats200ResponseInner
     */
    userEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ListChats200ResponseInner
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ListChats200ResponseInner
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListChats200ResponseInner
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the ListChats200ResponseInner interface.
 */
export function instanceOfListChats200ResponseInner(value: object): value is ListChats200ResponseInner {
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('userEmail' in value) || value['userEmail'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ListChats200ResponseInnerFromJSON(json: any): ListChats200ResponseInner {
    return ListChats200ResponseInnerFromJSONTyped(json, false);
}

export function ListChats200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListChats200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'roomId': json['room_id'],
        'userEmail': json['user_email'],
        'message': json['message'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function ListChats200ResponseInnerToJSON(value?: ListChats200ResponseInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'room_id': value['roomId'],
        'user_email': value['userEmail'],
        'message': value['message'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

