/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model225dcb39897141d8930dBc1334921194Request
 */
export interface Model225dcb39897141d8930dBc1334921194Request {
    [key: string]: any | any;
    /**
     * access_token or refresh_token
     * @type {string}
     * @memberof Model225dcb39897141d8930dBc1334921194Request
     */
    token: string;
}

/**
 * Check if a given object implements the Model225dcb39897141d8930dBc1334921194Request interface.
 */
export function instanceOfModel225dcb39897141d8930dBc1334921194Request(value: object): value is Model225dcb39897141d8930dBc1334921194Request {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function Model225dcb39897141d8930dBc1334921194RequestFromJSON(json: any): Model225dcb39897141d8930dBc1334921194Request {
    return Model225dcb39897141d8930dBc1334921194RequestFromJSONTyped(json, false);
}

export function Model225dcb39897141d8930dBc1334921194RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model225dcb39897141d8930dBc1334921194Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'token': json['token'],
    };
}

export function Model225dcb39897141d8930dBc1334921194RequestToJSON(value?: Model225dcb39897141d8930dBc1334921194Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'token': value['token'],
    };
}

