/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model1aaea97dFd544f01B912Cc8a942fa116Request
 */
export interface Model1aaea97dFd544f01B912Cc8a942fa116Request {
    [key: string]: any | any;
    /**
     * refresh_token
     * @type {string}
     * @memberof Model1aaea97dFd544f01B912Cc8a942fa116Request
     */
    token: string;
}

/**
 * Check if a given object implements the Model1aaea97dFd544f01B912Cc8a942fa116Request interface.
 */
export function instanceOfModel1aaea97dFd544f01B912Cc8a942fa116Request(value: object): value is Model1aaea97dFd544f01B912Cc8a942fa116Request {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function Model1aaea97dFd544f01B912Cc8a942fa116RequestFromJSON(json: any): Model1aaea97dFd544f01B912Cc8a942fa116Request {
    return Model1aaea97dFd544f01B912Cc8a942fa116RequestFromJSONTyped(json, false);
}

export function Model1aaea97dFd544f01B912Cc8a942fa116RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model1aaea97dFd544f01B912Cc8a942fa116Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'token': json['token'],
    };
}

export function Model1aaea97dFd544f01B912Cc8a942fa116RequestToJSON(value?: Model1aaea97dFd544f01B912Cc8a942fa116Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'token': value['token'],
    };
}

