/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model225dcb39897141d8930dBc1334921194200Response
 */
export interface Model225dcb39897141d8930dBc1334921194200Response {
    /**
     * 
     * @type {string}
     * @memberof Model225dcb39897141d8930dBc1334921194200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the Model225dcb39897141d8930dBc1334921194200Response interface.
 */
export function instanceOfModel225dcb39897141d8930dBc1334921194200Response(value: object): value is Model225dcb39897141d8930dBc1334921194200Response {
    return true;
}

export function Model225dcb39897141d8930dBc1334921194200ResponseFromJSON(json: any): Model225dcb39897141d8930dBc1334921194200Response {
    return Model225dcb39897141d8930dBc1334921194200ResponseFromJSONTyped(json, false);
}

export function Model225dcb39897141d8930dBc1334921194200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model225dcb39897141d8930dBc1334921194200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Model225dcb39897141d8930dBc1334921194200ResponseToJSON(value?: Model225dcb39897141d8930dBc1334921194200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

