/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationIab9v4baovn200Response
 */
export interface OperationIab9v4baovn200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationIab9v4baovn200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationIab9v4baovn200Response interface.
 */
export function instanceOfOperationIab9v4baovn200Response(value: object): value is OperationIab9v4baovn200Response {
    return true;
}

export function OperationIab9v4baovn200ResponseFromJSON(json: any): OperationIab9v4baovn200Response {
    return OperationIab9v4baovn200ResponseFromJSONTyped(json, false);
}

export function OperationIab9v4baovn200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationIab9v4baovn200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationIab9v4baovn200ResponseToJSON(value?: OperationIab9v4baovn200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

