/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Operation09x8p6105hqr200Response
 */
export interface Operation09x8p6105hqr200Response {
    /**
     * 
     * @type {string}
     * @memberof Operation09x8p6105hqr200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the Operation09x8p6105hqr200Response interface.
 */
export function instanceOfOperation09x8p6105hqr200Response(value: object): value is Operation09x8p6105hqr200Response {
    return true;
}

export function Operation09x8p6105hqr200ResponseFromJSON(json: any): Operation09x8p6105hqr200Response {
    return Operation09x8p6105hqr200ResponseFromJSONTyped(json, false);
}

export function Operation09x8p6105hqr200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation09x8p6105hqr200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function Operation09x8p6105hqr200ResponseToJSON(value?: Operation09x8p6105hqr200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

