/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationXpfmt7rtwb200Response
 */
export interface OperationXpfmt7rtwb200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationXpfmt7rtwb200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationXpfmt7rtwb200Response interface.
 */
export function instanceOfOperationXpfmt7rtwb200Response(value: object): value is OperationXpfmt7rtwb200Response {
    return true;
}

export function OperationXpfmt7rtwb200ResponseFromJSON(json: any): OperationXpfmt7rtwb200Response {
    return OperationXpfmt7rtwb200ResponseFromJSONTyped(json, false);
}

export function OperationXpfmt7rtwb200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationXpfmt7rtwb200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationXpfmt7rtwb200ResponseToJSON(value?: OperationXpfmt7rtwb200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

