/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationTmph7svoo5200Response
 */
export interface OperationTmph7svoo5200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationTmph7svoo5200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationTmph7svoo5200Response interface.
 */
export function instanceOfOperationTmph7svoo5200Response(value: object): value is OperationTmph7svoo5200Response {
    return true;
}

export function OperationTmph7svoo5200ResponseFromJSON(json: any): OperationTmph7svoo5200Response {
    return OperationTmph7svoo5200ResponseFromJSONTyped(json, false);
}

export function OperationTmph7svoo5200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationTmph7svoo5200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationTmph7svoo5200ResponseToJSON(value?: OperationTmph7svoo5200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

