/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationNogmw6kyvulRequest
 */
export interface OperationNogmw6kyvulRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationNogmw6kyvulRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationNogmw6kyvulRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationNogmw6kyvulRequest interface.
 */
export function instanceOfOperationNogmw6kyvulRequest(value: object): value is OperationNogmw6kyvulRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationNogmw6kyvulRequestFromJSON(json: any): OperationNogmw6kyvulRequest {
    return OperationNogmw6kyvulRequestFromJSONTyped(json, false);
}

export function OperationNogmw6kyvulRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationNogmw6kyvulRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationNogmw6kyvulRequestToJSON(value?: OperationNogmw6kyvulRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

