/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationLs9ps0tg6t200Response
 */
export interface OperationLs9ps0tg6t200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationLs9ps0tg6t200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationLs9ps0tg6t200Response interface.
 */
export function instanceOfOperationLs9ps0tg6t200Response(value: object): value is OperationLs9ps0tg6t200Response {
    return true;
}

export function OperationLs9ps0tg6t200ResponseFromJSON(json: any): OperationLs9ps0tg6t200Response {
    return OperationLs9ps0tg6t200ResponseFromJSONTyped(json, false);
}

export function OperationLs9ps0tg6t200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationLs9ps0tg6t200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationLs9ps0tg6t200ResponseToJSON(value?: OperationLs9ps0tg6t200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

