/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationVwwgyu8hyxpRequest
 */
export interface OperationVwwgyu8hyxpRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationVwwgyu8hyxpRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationVwwgyu8hyxpRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationVwwgyu8hyxpRequest interface.
 */
export function instanceOfOperationVwwgyu8hyxpRequest(value: object): value is OperationVwwgyu8hyxpRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationVwwgyu8hyxpRequestFromJSON(json: any): OperationVwwgyu8hyxpRequest {
    return OperationVwwgyu8hyxpRequestFromJSONTyped(json, false);
}

export function OperationVwwgyu8hyxpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationVwwgyu8hyxpRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationVwwgyu8hyxpRequestToJSON(value?: OperationVwwgyu8hyxpRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

