/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Operation86aq7gn6wpRequest
 */
export interface Operation86aq7gn6wpRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Operation86aq7gn6wpRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof Operation86aq7gn6wpRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the Operation86aq7gn6wpRequest interface.
 */
export function instanceOfOperation86aq7gn6wpRequest(value: object): value is Operation86aq7gn6wpRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function Operation86aq7gn6wpRequestFromJSON(json: any): Operation86aq7gn6wpRequest {
    return Operation86aq7gn6wpRequestFromJSONTyped(json, false);
}

export function Operation86aq7gn6wpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation86aq7gn6wpRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function Operation86aq7gn6wpRequestToJSON(value?: Operation86aq7gn6wpRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

