/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationKlrj8soohrRequest
 */
export interface OperationKlrj8soohrRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationKlrj8soohrRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationKlrj8soohrRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationKlrj8soohrRequest interface.
 */
export function instanceOfOperationKlrj8soohrRequest(value: object): value is OperationKlrj8soohrRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationKlrj8soohrRequestFromJSON(json: any): OperationKlrj8soohrRequest {
    return OperationKlrj8soohrRequestFromJSONTyped(json, false);
}

export function OperationKlrj8soohrRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationKlrj8soohrRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationKlrj8soohrRequestToJSON(value?: OperationKlrj8soohrRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

