/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationNogmw6kyvul200Response
 */
export interface OperationNogmw6kyvul200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationNogmw6kyvul200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationNogmw6kyvul200Response interface.
 */
export function instanceOfOperationNogmw6kyvul200Response(value: object): value is OperationNogmw6kyvul200Response {
    return true;
}

export function OperationNogmw6kyvul200ResponseFromJSON(json: any): OperationNogmw6kyvul200Response {
    return OperationNogmw6kyvul200ResponseFromJSONTyped(json, false);
}

export function OperationNogmw6kyvul200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationNogmw6kyvul200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationNogmw6kyvul200ResponseToJSON(value?: OperationNogmw6kyvul200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

