/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationMn2us6r0s1fRequest
 */
export interface OperationMn2us6r0s1fRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationMn2us6r0s1fRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationMn2us6r0s1fRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationMn2us6r0s1fRequest interface.
 */
export function instanceOfOperationMn2us6r0s1fRequest(value: object): value is OperationMn2us6r0s1fRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationMn2us6r0s1fRequestFromJSON(json: any): OperationMn2us6r0s1fRequest {
    return OperationMn2us6r0s1fRequestFromJSONTyped(json, false);
}

export function OperationMn2us6r0s1fRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationMn2us6r0s1fRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationMn2us6r0s1fRequestToJSON(value?: OperationMn2us6r0s1fRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

