/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationNvvj718bbmRequest
 */
export interface OperationNvvj718bbmRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationNvvj718bbmRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationNvvj718bbmRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationNvvj718bbmRequest interface.
 */
export function instanceOfOperationNvvj718bbmRequest(value: object): value is OperationNvvj718bbmRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationNvvj718bbmRequestFromJSON(json: any): OperationNvvj718bbmRequest {
    return OperationNvvj718bbmRequestFromJSONTyped(json, false);
}

export function OperationNvvj718bbmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationNvvj718bbmRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationNvvj718bbmRequestToJSON(value?: OperationNvvj718bbmRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

