/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationGjwoojaj2hRequest
 */
export interface OperationGjwoojaj2hRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationGjwoojaj2hRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationGjwoojaj2hRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationGjwoojaj2hRequest interface.
 */
export function instanceOfOperationGjwoojaj2hRequest(value: object): value is OperationGjwoojaj2hRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationGjwoojaj2hRequestFromJSON(json: any): OperationGjwoojaj2hRequest {
    return OperationGjwoojaj2hRequestFromJSONTyped(json, false);
}

export function OperationGjwoojaj2hRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationGjwoojaj2hRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationGjwoojaj2hRequestToJSON(value?: OperationGjwoojaj2hRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

