/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationOy0187p9gqdRequest
 */
export interface OperationOy0187p9gqdRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationOy0187p9gqdRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationOy0187p9gqdRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationOy0187p9gqdRequest interface.
 */
export function instanceOfOperationOy0187p9gqdRequest(value: object): value is OperationOy0187p9gqdRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationOy0187p9gqdRequestFromJSON(json: any): OperationOy0187p9gqdRequest {
    return OperationOy0187p9gqdRequestFromJSONTyped(json, false);
}

export function OperationOy0187p9gqdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationOy0187p9gqdRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationOy0187p9gqdRequestToJSON(value?: OperationOy0187p9gqdRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

