/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationYh6zudk8kd8200Response
 */
export interface OperationYh6zudk8kd8200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationYh6zudk8kd8200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationYh6zudk8kd8200Response interface.
 */
export function instanceOfOperationYh6zudk8kd8200Response(value: object): value is OperationYh6zudk8kd8200Response {
    return true;
}

export function OperationYh6zudk8kd8200ResponseFromJSON(json: any): OperationYh6zudk8kd8200Response {
    return OperationYh6zudk8kd8200ResponseFromJSONTyped(json, false);
}

export function OperationYh6zudk8kd8200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationYh6zudk8kd8200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationYh6zudk8kd8200ResponseToJSON(value?: OperationYh6zudk8kd8200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

