/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationN2jqxrl57x8200Response
 */
export interface OperationN2jqxrl57x8200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationN2jqxrl57x8200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationN2jqxrl57x8200Response interface.
 */
export function instanceOfOperationN2jqxrl57x8200Response(value: object): value is OperationN2jqxrl57x8200Response {
    return true;
}

export function OperationN2jqxrl57x8200ResponseFromJSON(json: any): OperationN2jqxrl57x8200Response {
    return OperationN2jqxrl57x8200ResponseFromJSONTyped(json, false);
}

export function OperationN2jqxrl57x8200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationN2jqxrl57x8200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationN2jqxrl57x8200ResponseToJSON(value?: OperationN2jqxrl57x8200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

