/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Operation1xn3emb73f1200Response
 */
export interface Operation1xn3emb73f1200Response {
    /**
     * 
     * @type {string}
     * @memberof Operation1xn3emb73f1200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the Operation1xn3emb73f1200Response interface.
 */
export function instanceOfOperation1xn3emb73f1200Response(value: object): value is Operation1xn3emb73f1200Response {
    return true;
}

export function Operation1xn3emb73f1200ResponseFromJSON(json: any): Operation1xn3emb73f1200Response {
    return Operation1xn3emb73f1200ResponseFromJSONTyped(json, false);
}

export function Operation1xn3emb73f1200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation1xn3emb73f1200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function Operation1xn3emb73f1200ResponseToJSON(value?: Operation1xn3emb73f1200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

