/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationH7i8dq24pmgRequest
 */
export interface OperationH7i8dq24pmgRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationH7i8dq24pmgRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationH7i8dq24pmgRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationH7i8dq24pmgRequest interface.
 */
export function instanceOfOperationH7i8dq24pmgRequest(value: object): value is OperationH7i8dq24pmgRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationH7i8dq24pmgRequestFromJSON(json: any): OperationH7i8dq24pmgRequest {
    return OperationH7i8dq24pmgRequestFromJSONTyped(json, false);
}

export function OperationH7i8dq24pmgRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationH7i8dq24pmgRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationH7i8dq24pmgRequestToJSON(value?: OperationH7i8dq24pmgRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

