/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationCdno3avq0jo200Response
 */
export interface OperationCdno3avq0jo200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationCdno3avq0jo200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationCdno3avq0jo200Response interface.
 */
export function instanceOfOperationCdno3avq0jo200Response(value: object): value is OperationCdno3avq0jo200Response {
    return true;
}

export function OperationCdno3avq0jo200ResponseFromJSON(json: any): OperationCdno3avq0jo200Response {
    return OperationCdno3avq0jo200ResponseFromJSONTyped(json, false);
}

export function OperationCdno3avq0jo200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationCdno3avq0jo200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationCdno3avq0jo200ResponseToJSON(value?: OperationCdno3avq0jo200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

