/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationN2jqxrl57x8Request
 */
export interface OperationN2jqxrl57x8Request {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationN2jqxrl57x8Request
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationN2jqxrl57x8Request
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationN2jqxrl57x8Request interface.
 */
export function instanceOfOperationN2jqxrl57x8Request(value: object): value is OperationN2jqxrl57x8Request {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationN2jqxrl57x8RequestFromJSON(json: any): OperationN2jqxrl57x8Request {
    return OperationN2jqxrl57x8RequestFromJSONTyped(json, false);
}

export function OperationN2jqxrl57x8RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationN2jqxrl57x8Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationN2jqxrl57x8RequestToJSON(value?: OperationN2jqxrl57x8Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

