/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationKlrj8soohr200Response
 */
export interface OperationKlrj8soohr200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationKlrj8soohr200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationKlrj8soohr200Response interface.
 */
export function instanceOfOperationKlrj8soohr200Response(value: object): value is OperationKlrj8soohr200Response {
    return true;
}

export function OperationKlrj8soohr200ResponseFromJSON(json: any): OperationKlrj8soohr200Response {
    return OperationKlrj8soohr200ResponseFromJSONTyped(json, false);
}

export function OperationKlrj8soohr200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationKlrj8soohr200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationKlrj8soohr200ResponseToJSON(value?: OperationKlrj8soohr200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

