/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationWc79cuoakf200Response
 */
export interface OperationWc79cuoakf200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationWc79cuoakf200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationWc79cuoakf200Response interface.
 */
export function instanceOfOperationWc79cuoakf200Response(value: object): value is OperationWc79cuoakf200Response {
    return true;
}

export function OperationWc79cuoakf200ResponseFromJSON(json: any): OperationWc79cuoakf200Response {
    return OperationWc79cuoakf200ResponseFromJSONTyped(json, false);
}

export function OperationWc79cuoakf200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationWc79cuoakf200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationWc79cuoakf200ResponseToJSON(value?: OperationWc79cuoakf200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

