/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationSr98pp15v9Request
 */
export interface OperationSr98pp15v9Request {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationSr98pp15v9Request
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationSr98pp15v9Request
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationSr98pp15v9Request interface.
 */
export function instanceOfOperationSr98pp15v9Request(value: object): value is OperationSr98pp15v9Request {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationSr98pp15v9RequestFromJSON(json: any): OperationSr98pp15v9Request {
    return OperationSr98pp15v9RequestFromJSONTyped(json, false);
}

export function OperationSr98pp15v9RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationSr98pp15v9Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationSr98pp15v9RequestToJSON(value?: OperationSr98pp15v9Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

