/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationHfdl0ff9m7nRequest
 */
export interface OperationHfdl0ff9m7nRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationHfdl0ff9m7nRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationHfdl0ff9m7nRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationHfdl0ff9m7nRequest interface.
 */
export function instanceOfOperationHfdl0ff9m7nRequest(value: object): value is OperationHfdl0ff9m7nRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationHfdl0ff9m7nRequestFromJSON(json: any): OperationHfdl0ff9m7nRequest {
    return OperationHfdl0ff9m7nRequestFromJSONTyped(json, false);
}

export function OperationHfdl0ff9m7nRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationHfdl0ff9m7nRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationHfdl0ff9m7nRequestToJSON(value?: OperationHfdl0ff9m7nRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

