/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationOy0187p9gqd200Response
 */
export interface OperationOy0187p9gqd200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationOy0187p9gqd200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationOy0187p9gqd200Response interface.
 */
export function instanceOfOperationOy0187p9gqd200Response(value: object): value is OperationOy0187p9gqd200Response {
    return true;
}

export function OperationOy0187p9gqd200ResponseFromJSON(json: any): OperationOy0187p9gqd200Response {
    return OperationOy0187p9gqd200ResponseFromJSONTyped(json, false);
}

export function OperationOy0187p9gqd200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationOy0187p9gqd200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationOy0187p9gqd200ResponseToJSON(value?: OperationOy0187p9gqd200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

