/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationLs9ps0tg6tRequest
 */
export interface OperationLs9ps0tg6tRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationLs9ps0tg6tRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationLs9ps0tg6tRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationLs9ps0tg6tRequest interface.
 */
export function instanceOfOperationLs9ps0tg6tRequest(value: object): value is OperationLs9ps0tg6tRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationLs9ps0tg6tRequestFromJSON(json: any): OperationLs9ps0tg6tRequest {
    return OperationLs9ps0tg6tRequestFromJSONTyped(json, false);
}

export function OperationLs9ps0tg6tRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationLs9ps0tg6tRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationLs9ps0tg6tRequestToJSON(value?: OperationLs9ps0tg6tRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

