/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationCdno3avq0joRequest
 */
export interface OperationCdno3avq0joRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationCdno3avq0joRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationCdno3avq0joRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationCdno3avq0joRequest interface.
 */
export function instanceOfOperationCdno3avq0joRequest(value: object): value is OperationCdno3avq0joRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationCdno3avq0joRequestFromJSON(json: any): OperationCdno3avq0joRequest {
    return OperationCdno3avq0joRequestFromJSONTyped(json, false);
}

export function OperationCdno3avq0joRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationCdno3avq0joRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationCdno3avq0joRequestToJSON(value?: OperationCdno3avq0joRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

