/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationNvvj718bbm200Response
 */
export interface OperationNvvj718bbm200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationNvvj718bbm200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationNvvj718bbm200Response interface.
 */
export function instanceOfOperationNvvj718bbm200Response(value: object): value is OperationNvvj718bbm200Response {
    return true;
}

export function OperationNvvj718bbm200ResponseFromJSON(json: any): OperationNvvj718bbm200Response {
    return OperationNvvj718bbm200ResponseFromJSONTyped(json, false);
}

export function OperationNvvj718bbm200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationNvvj718bbm200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationNvvj718bbm200ResponseToJSON(value?: OperationNvvj718bbm200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

