/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationXpfmt7rtwbRequest
 */
export interface OperationXpfmt7rtwbRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationXpfmt7rtwbRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationXpfmt7rtwbRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationXpfmt7rtwbRequest interface.
 */
export function instanceOfOperationXpfmt7rtwbRequest(value: object): value is OperationXpfmt7rtwbRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationXpfmt7rtwbRequestFromJSON(json: any): OperationXpfmt7rtwbRequest {
    return OperationXpfmt7rtwbRequestFromJSONTyped(json, false);
}

export function OperationXpfmt7rtwbRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationXpfmt7rtwbRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationXpfmt7rtwbRequestToJSON(value?: OperationXpfmt7rtwbRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

