/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Operation1xn3emb73f1Request
 */
export interface Operation1xn3emb73f1Request {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Operation1xn3emb73f1Request
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof Operation1xn3emb73f1Request
     */
    name?: string;
}

/**
 * Check if a given object implements the Operation1xn3emb73f1Request interface.
 */
export function instanceOfOperation1xn3emb73f1Request(value: object): value is Operation1xn3emb73f1Request {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function Operation1xn3emb73f1RequestFromJSON(json: any): Operation1xn3emb73f1Request {
    return Operation1xn3emb73f1RequestFromJSONTyped(json, false);
}

export function Operation1xn3emb73f1RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation1xn3emb73f1Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function Operation1xn3emb73f1RequestToJSON(value?: Operation1xn3emb73f1Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

