/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationYh6zudk8kd8Request
 */
export interface OperationYh6zudk8kd8Request {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationYh6zudk8kd8Request
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationYh6zudk8kd8Request
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationYh6zudk8kd8Request interface.
 */
export function instanceOfOperationYh6zudk8kd8Request(value: object): value is OperationYh6zudk8kd8Request {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationYh6zudk8kd8RequestFromJSON(json: any): OperationYh6zudk8kd8Request {
    return OperationYh6zudk8kd8RequestFromJSONTyped(json, false);
}

export function OperationYh6zudk8kd8RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationYh6zudk8kd8Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationYh6zudk8kd8RequestToJSON(value?: OperationYh6zudk8kd8Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

