/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationWc79cuoakfRequest
 */
export interface OperationWc79cuoakfRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationWc79cuoakfRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationWc79cuoakfRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationWc79cuoakfRequest interface.
 */
export function instanceOfOperationWc79cuoakfRequest(value: object): value is OperationWc79cuoakfRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationWc79cuoakfRequestFromJSON(json: any): OperationWc79cuoakfRequest {
    return OperationWc79cuoakfRequestFromJSONTyped(json, false);
}

export function OperationWc79cuoakfRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationWc79cuoakfRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationWc79cuoakfRequestToJSON(value?: OperationWc79cuoakfRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

