/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationHfdl0ff9m7n200Response
 */
export interface OperationHfdl0ff9m7n200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationHfdl0ff9m7n200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationHfdl0ff9m7n200Response interface.
 */
export function instanceOfOperationHfdl0ff9m7n200Response(value: object): value is OperationHfdl0ff9m7n200Response {
    return true;
}

export function OperationHfdl0ff9m7n200ResponseFromJSON(json: any): OperationHfdl0ff9m7n200Response {
    return OperationHfdl0ff9m7n200ResponseFromJSONTyped(json, false);
}

export function OperationHfdl0ff9m7n200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationHfdl0ff9m7n200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationHfdl0ff9m7n200ResponseToJSON(value?: OperationHfdl0ff9m7n200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

