/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Operation86aq7gn6wp200Response
 */
export interface Operation86aq7gn6wp200Response {
    /**
     * 
     * @type {string}
     * @memberof Operation86aq7gn6wp200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the Operation86aq7gn6wp200Response interface.
 */
export function instanceOfOperation86aq7gn6wp200Response(value: object): value is Operation86aq7gn6wp200Response {
    return true;
}

export function Operation86aq7gn6wp200ResponseFromJSON(json: any): Operation86aq7gn6wp200Response {
    return Operation86aq7gn6wp200ResponseFromJSONTyped(json, false);
}

export function Operation86aq7gn6wp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Operation86aq7gn6wp200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function Operation86aq7gn6wp200ResponseToJSON(value?: Operation86aq7gn6wp200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

