/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationTmph7svoo5Request
 */
export interface OperationTmph7svoo5Request {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationTmph7svoo5Request
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationTmph7svoo5Request
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationTmph7svoo5Request interface.
 */
export function instanceOfOperationTmph7svoo5Request(value: object): value is OperationTmph7svoo5Request {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationTmph7svoo5RequestFromJSON(json: any): OperationTmph7svoo5Request {
    return OperationTmph7svoo5RequestFromJSONTyped(json, false);
}

export function OperationTmph7svoo5RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationTmph7svoo5Request {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationTmph7svoo5RequestToJSON(value?: OperationTmph7svoo5Request | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

