/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationGjwoojaj2h200Response
 */
export interface OperationGjwoojaj2h200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationGjwoojaj2h200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationGjwoojaj2h200Response interface.
 */
export function instanceOfOperationGjwoojaj2h200Response(value: object): value is OperationGjwoojaj2h200Response {
    return true;
}

export function OperationGjwoojaj2h200ResponseFromJSON(json: any): OperationGjwoojaj2h200Response {
    return OperationGjwoojaj2h200ResponseFromJSONTyped(json, false);
}

export function OperationGjwoojaj2h200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationGjwoojaj2h200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationGjwoojaj2h200ResponseToJSON(value?: OperationGjwoojaj2h200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

