/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationU3a4wzlkjvmRequest
 */
export interface OperationU3a4wzlkjvmRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationU3a4wzlkjvmRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationU3a4wzlkjvmRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationU3a4wzlkjvmRequest interface.
 */
export function instanceOfOperationU3a4wzlkjvmRequest(value: object): value is OperationU3a4wzlkjvmRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationU3a4wzlkjvmRequestFromJSON(json: any): OperationU3a4wzlkjvmRequest {
    return OperationU3a4wzlkjvmRequestFromJSONTyped(json, false);
}

export function OperationU3a4wzlkjvmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationU3a4wzlkjvmRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationU3a4wzlkjvmRequestToJSON(value?: OperationU3a4wzlkjvmRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

