/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationX7csssz5hs200Response
 */
export interface OperationX7csssz5hs200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationX7csssz5hs200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationX7csssz5hs200Response interface.
 */
export function instanceOfOperationX7csssz5hs200Response(value: object): value is OperationX7csssz5hs200Response {
    return true;
}

export function OperationX7csssz5hs200ResponseFromJSON(json: any): OperationX7csssz5hs200Response {
    return OperationX7csssz5hs200ResponseFromJSONTyped(json, false);
}

export function OperationX7csssz5hs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationX7csssz5hs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationX7csssz5hs200ResponseToJSON(value?: OperationX7csssz5hs200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

