/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationX7csssz5hsRequest
 */
export interface OperationX7csssz5hsRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof OperationX7csssz5hsRequest
     */
    fileId: string;
    /**
     * 
     * @type {string}
     * @memberof OperationX7csssz5hsRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OperationX7csssz5hsRequest interface.
 */
export function instanceOfOperationX7csssz5hsRequest(value: object): value is OperationX7csssz5hsRequest {
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function OperationX7csssz5hsRequestFromJSON(json: any): OperationX7csssz5hsRequest {
    return OperationX7csssz5hsRequestFromJSONTyped(json, false);
}

export function OperationX7csssz5hsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationX7csssz5hsRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'fileId': json['file_id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OperationX7csssz5hsRequestToJSON(value?: OperationX7csssz5hsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'file_id': value['fileId'],
        'name': value['name'],
    };
}

