/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationH7i8dq24pmg200Response
 */
export interface OperationH7i8dq24pmg200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationH7i8dq24pmg200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationH7i8dq24pmg200Response interface.
 */
export function instanceOfOperationH7i8dq24pmg200Response(value: object): value is OperationH7i8dq24pmg200Response {
    return true;
}

export function OperationH7i8dq24pmg200ResponseFromJSON(json: any): OperationH7i8dq24pmg200Response {
    return OperationH7i8dq24pmg200ResponseFromJSONTyped(json, false);
}

export function OperationH7i8dq24pmg200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationH7i8dq24pmg200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationH7i8dq24pmg200ResponseToJSON(value?: OperationH7i8dq24pmg200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

