/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationSr98pp15v9200Response
 */
export interface OperationSr98pp15v9200Response {
    /**
     * 
     * @type {string}
     * @memberof OperationSr98pp15v9200Response
     */
    url?: string;
}

/**
 * Check if a given object implements the OperationSr98pp15v9200Response interface.
 */
export function instanceOfOperationSr98pp15v9200Response(value: object): value is OperationSr98pp15v9200Response {
    return true;
}

export function OperationSr98pp15v9200ResponseFromJSON(json: any): OperationSr98pp15v9200Response {
    return OperationSr98pp15v9200ResponseFromJSONTyped(json, false);
}

export function OperationSr98pp15v9200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationSr98pp15v9200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function OperationSr98pp15v9200ResponseToJSON(value?: OperationSr98pp15v9200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
    };
}

