/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskRequest
 */
export interface UpdateTaskRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    taskStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    dueDate?: string;
}

/**
 * Check if a given object implements the UpdateTaskRequest interface.
 */
export function instanceOfUpdateTaskRequest(value: object): value is UpdateTaskRequest {
    return true;
}

export function UpdateTaskRequestFromJSON(json: any): UpdateTaskRequest {
    return UpdateTaskRequestFromJSONTyped(json, false);
}

export function UpdateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'taskStatus': json['task_status'] == null ? undefined : json['task_status'],
        'dueDate': json['due_date'] == null ? undefined : json['due_date'],
    };
}

export function UpdateTaskRequestToJSON(value?: UpdateTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'title': value['title'],
        'description': value['description'],
        'task_status': value['taskStatus'],
        'due_date': value['dueDate'],
    };
}

