/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateIssueRequest
 */
export interface UpdateIssueRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof UpdateIssueRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateIssueRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateIssueRequest
     */
    issueStatus?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateIssueRequest
     */
    dueDate?: string;
}

/**
 * Check if a given object implements the UpdateIssueRequest interface.
 */
export function instanceOfUpdateIssueRequest(value: object): value is UpdateIssueRequest {
    return true;
}

export function UpdateIssueRequestFromJSON(json: any): UpdateIssueRequest {
    return UpdateIssueRequestFromJSONTyped(json, false);
}

export function UpdateIssueRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateIssueRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'issueStatus': json['issue_status'] == null ? undefined : json['issue_status'],
        'dueDate': json['due_date'] == null ? undefined : json['due_date'],
    };
}

export function UpdateIssueRequestToJSON(value?: UpdateIssueRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'title': value['title'],
        'description': value['description'],
        'issue_status': value['issueStatus'],
        'due_date': value['dueDate'],
    };
}

