/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AuthGoogleRevokePost200Response
 */
export interface V1AuthGoogleRevokePost200Response {
    /**
     * 
     * @type {string}
     * @memberof V1AuthGoogleRevokePost200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the V1AuthGoogleRevokePost200Response interface.
 */
export function instanceOfV1AuthGoogleRevokePost200Response(value: object): value is V1AuthGoogleRevokePost200Response {
    return true;
}

export function V1AuthGoogleRevokePost200ResponseFromJSON(json: any): V1AuthGoogleRevokePost200Response {
    return V1AuthGoogleRevokePost200ResponseFromJSONTyped(json, false);
}

export function V1AuthGoogleRevokePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AuthGoogleRevokePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function V1AuthGoogleRevokePost200ResponseToJSON(value?: V1AuthGoogleRevokePost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

