/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AuthGoogleRevokePostRequest
 */
export interface V1AuthGoogleRevokePostRequest {
    [key: string]: any | any;
    /**
     * access_token or refresh_token
     * @type {string}
     * @memberof V1AuthGoogleRevokePostRequest
     */
    token: string;
}

/**
 * Check if a given object implements the V1AuthGoogleRevokePostRequest interface.
 */
export function instanceOfV1AuthGoogleRevokePostRequest(value: object): value is V1AuthGoogleRevokePostRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function V1AuthGoogleRevokePostRequestFromJSON(json: any): V1AuthGoogleRevokePostRequest {
    return V1AuthGoogleRevokePostRequestFromJSONTyped(json, false);
}

export function V1AuthGoogleRevokePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AuthGoogleRevokePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'token': json['token'],
    };
}

export function V1AuthGoogleRevokePostRequestToJSON(value?: V1AuthGoogleRevokePostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'token': value['token'],
    };
}

