version = 0.1
[default.deploy.parameters]
stack_name = "tms-app"
resolve_s3 = true
s3_prefix = "tms-app"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
config-env= ".env"
debug=true